CFLAGS += -O3 -Wall -std=gnu99 -g -lm

all: forward back left right stop led fun spin right45 left45

clean: 
	rm forward back left right stop led fun spin right45 left45
	
forward: uart.c forward.c
back: uart.c back.c
left: uart.c left.c
right: uart.c right.c
stop: uart.c stop.c
led: uart.c led.c
fun: uart.c fun.c
spin: uart.c spin.c
right45: uart.c right45.c
left45: uart.c left45.c


